
ORDERS = {
    "HT1001": {
        "order_id": "HT1001",
        "email": "alice@example.com",
        "status": "Processing",
        "items": [{"sku": "TSHIRT-RED", "qty": 1, "name": "Red T-Shirt"}],
        "shipment": {"carrier": "FastShip", "tracking": "FS1001", "status": "Label created"},
        "payment": {"method": "Visa", "status": "Paid", "last4": "4242"},
        "invoice": {"url": "https://example.com/invoice/HT1001", "amount": 29.99},
        "refund": {"status": "None", "amount": 0.0},
    },
    "HT1002": {
        "order_id": "HT1002",
        "email": "bob@example.com",
        "status": "Shipped",
        "items": [{"sku": "MUG-LOGO", "qty": 2, "name": "Logo Mug"}],
        "shipment": {"carrier": "ShipQuick", "tracking": "SQ1002", "status": "In transit"},
        "payment": {"method": "PayPal", "status": "Paid", "txn": "PP1002"},
        "invoice": {"url": "https://example.com/invoice/HT1002", "amount": 39.98},
        "refund": {"status": "None", "amount": 0.0},
    },
    "HT1003": {
        "order_id": "HT1003",
        "email": "carol@example.com",
        "status": "Delivered",
        "items": [{"sku": "HAT-BLACK", "qty": 1, "name": "Black Hat"}],
        "shipment": {"carrier": "FastShip", "tracking": "FS1003", "status": "Delivered"},
        "payment": {"method": "Mastercard", "status": "Paid", "last4": "1111"},
        "invoice": {"url": "https://example.com/invoice/HT1003", "amount": 19.99},
        "refund": {"status": "None", "amount": 0.0},
    },
    "HT1004": {
        "order_id": "HT1004",
        "email": "dave@example.com",
        "status": "Cancelled",
        "items": [{"sku": "POSTER-XL", "qty": 1, "name": "XL Poster"}],
        "shipment": {"carrier": "", "tracking": "", "status": "Not shipped"},
        "payment": {"method": "Visa", "status": "Refunded", "last4": "2222"},
        "invoice": {"url": "https://example.com/invoice/HT1004", "amount": 14.99},
        "refund": {"status": "Completed", "amount": 14.99},
    },
    "HT1005": {
        "order_id": "HT1005",
        "email": "eve@example.com",
        "status": "Processing",
        "items": [{"sku": "HOODIE-GRAY", "qty": 1, "name": "Gray Hoodie"}],
        "shipment": {"carrier": "ShipQuick", "tracking": "SQ1005", "status": "Label created"},
        "payment": {"method": "Amex", "status": "Pending"},
        "invoice": {"url": "https://example.com/invoice/HT1005", "amount": 59.99},
        "refund": {"status": "None", "amount": 0.0},
    },
    "HT1006": {
        "order_id": "HT1006",
        "email": "frank@example.com",
        "status": "Shipped",
        "items": [{"sku": "SOCKS-3PK", "qty": 1, "name": "Socks 3-pack"}],
        "shipment": {"carrier": "FastShip", "tracking": "FS1006", "status": "In transit"},
        "payment": {"method": "Visa", "status": "Paid", "last4": "3333"},
        "invoice": {"url": "https://example.com/invoice/HT1006", "amount": 9.99},
        "refund": {"status": "None", "amount": 0.0},
    },
    "HT1007": {
        "order_id": "HT1007",
        "email": "grace@example.com",
        "status": "Delivered",
        "items": [{"sku": "BAG-CANVAS", "qty": 1, "name": "Canvas Bag"}],
        "shipment": {"carrier": "ShipQuick", "tracking": "SQ1007", "status": "Delivered"},
        "payment": {"method": "PayPal", "status": "Paid", "txn": "PP1007"},
        "invoice": {"url": "https://example.com/invoice/HT1007", "amount": 24.99},
        "refund": {"status": "None", "amount": 0.0},
    },
    "HT1008": {
        "order_id": "HT1008",
        "email": "henry@example.com",
        "status": "Processing",
        "items": [{"sku": "STICKER-SET", "qty": 1, "name": "Sticker Set"}],
        "shipment": {"carrier": "FastShip", "tracking": "FS1008", "status": "Label created"},
        "payment": {"method": "Visa", "status": "Paid", "last4": "4444"},
        "invoice": {"url": "https://example.com/invoice/HT1008", "amount": 4.99},
        "refund": {"status": "None", "amount": 0.0},
    },
    "HT1009": {
        "order_id": "HT1009",
        "email": "ivy@example.com",
        "status": "Shipped",
        "items": [{"sku": "NECKLACE-SILVER", "qty": 1, "name": "Silver Necklace"}],
        "shipment": {"carrier": "ShipQuick", "tracking": "SQ1009", "status": "In transit"},
        "payment": {"method": "Mastercard", "status": "Paid", "last4": "5555"},
        "invoice": {"url": "https://example.com/invoice/HT1009", "amount": 79.99},
        "refund": {"status": "None", "amount": 0.0},
    },
    "HT1010": {
        "order_id": "HT1010",
        "email": "jack@example.com",
        "status": "Delivered",
        "items": [{"sku": "BOOK-001", "qty": 1, "name": "How To Shop"}],
        "shipment": {"carrier": "FastShip", "tracking": "FS1010", "status": "Delivered"},
        "payment": {"method": "Visa", "status": "Paid", "last4": "6666"},
        "invoice": {"url": "https://example.com/invoice/HT1010", "amount": 12.5},
        "refund": {"status": "None", "amount": 0.0},
    },
    "HT1011": {
        "order_id": "HT1011",
        "email": "kate@example.com",
        "status": "Processing",
        "items": [{"sku": "PEN-GOLD", "qty": 1, "name": "Gold Pen"}],
        "shipment": {"carrier": "ShipQuick", "tracking": "SQ1011", "status": "Label created"},
        "payment": {"method": "Amex", "status": "Paid"},
        "invoice": {"url": "https://example.com/invoice/HT1011", "amount": 7.5},
        "refund": {"status": "None", "amount": 0.0},
    },
    "HT1012": {
        "order_id": "HT1012",
        "email": "leo@example.com",
        "status": "Shipped",
        "items": [{"sku": "WATER-BOTTLE", "qty": 1, "name": "Water Bottle"}],
        "shipment": {"carrier": "FastShip", "tracking": "FS1012", "status": "In transit"},
        "payment": {"method": "Visa", "status": "Paid", "last4": "7777"},
        "invoice": {"url": "https://example.com/invoice/HT1012", "amount": 15.0},
        "refund": {"status": "None", "amount": 0.0},
    },
    "HT1013": {
        "order_id": "HT1013",
        "email": "mia@example.com",
        "status": "Delivered",
        "items": [{"sku": "NOTEPAD-A5", "qty": 1, "name": "A5 Notepad"}],
        "shipment": {"carrier": "ShipQuick", "tracking": "SQ1013", "status": "Delivered"},
        "payment": {"method": "PayPal", "status": "Paid", "txn": "PP1013"},
        "invoice": {"url": "https://example.com/invoice/HT1013", "amount": 6.75},
        "refund": {"status": "None", "amount": 0.0},
    },
    "HT1014": {
        "order_id": "HT1014",
        "email": "noah@example.com",
        "status": "Processing",
        "items": [{"sku": "CHARGER-USB", "qty": 1, "name": "USB Charger"}],
        "shipment": {"carrier": "FastShip", "tracking": "FS1014", "status": "Label created"},
        "payment": {"method": "Visa", "status": "Pending"},
        "invoice": {"url": "https://example.com/invoice/HT1014", "amount": 11.0},
        "refund": {"status": "None", "amount": 0.0},
    },
    "HT1015": {
        "order_id": "HT1015",
        "email": "olivia@example.com",
        "status": "Shipped",
        "items": [{"sku": "PHONE-CASE", "qty": 1, "name": "Phone Case"}],
        "shipment": {"carrier": "ShipQuick", "tracking": "SQ1015", "status": "In transit"},
        "payment": {"method": "Mastercard", "status": "Paid", "last4": "8888"},
        "invoice": {"url": "https://example.com/invoice/HT1015", "amount": 18.0},
        "refund": {"status": "None", "amount": 0.0},
    },
    "HT1016": {
        "order_id": "HT1016",
        "email": "peter@example.com",
        "status": "Delivered",
        "items": [{"sku": "KEYCHAIN", "qty": 1, "name": "Keychain"}],
        "shipment": {"carrier": "FastShip", "tracking": "FS1016", "status": "Delivered"},
        "payment": {"method": "Visa", "status": "Paid", "last4": "9999"},
        "invoice": {"url": "https://example.com/invoice/HT1016", "amount": 3.5},
        "refund": {"status": "None", "amount": 0.0},
    },
    "HT1017": {
        "order_id": "HT1017",
        "email": "quinn@example.com",
        "status": "Processing",
        "items": [{"sku": "CARD-GIFT", "qty": 1, "name": "Gift Card"}],
        "shipment": {"carrier": "", "tracking": "", "status": "Digital"},
        "payment": {"method": "PayPal", "status": "Paid", "txn": "PP1017"},
        "invoice": {"url": "https://example.com/invoice/HT1017", "amount": 50.0},
        "refund": {"status": "None", "amount": 0.0},
    },
    "HT1018": {
        "order_id": "HT1018",
        "email": "rachel@example.com",
        "status": "Shipped",
        "items": [{"sku": "LENS-CLEAN", "qty": 1, "name": "Lens Cleaner"}],
        "shipment": {"carrier": "ShipQuick", "tracking": "SQ1018", "status": "In transit"},
        "payment": {"method": "Visa", "status": "Paid", "last4": "0001"},
        "invoice": {"url": "https://example.com/invoice/HT1018", "amount": 5.25},
        "refund": {"status": "None", "amount": 0.0},
    },
    "HT1019": {
        "order_id": "HT1019",
        "email": "sam@example.com",
        "status": "Delivered",
        "items": [{"sku": "BLUETOOTH-SPEAKER", "qty": 1, "name": "Bluetooth Speaker"}],
        "shipment": {"carrier": "FastShip", "tracking": "FS1019", "status": "Delivered"},
        "payment": {"method": "Mastercard", "status": "Paid", "last4": "2223"},
        "invoice": {"url": "https://example.com/invoice/HT1019", "amount": 45.0},
        "refund": {"status": "None", "amount": 0.0},
    },
    "HT1020": {
        "order_id": "HT1020",
        "email": "tina@example.com",
        "status": "Processing",
        "items": [{"sku": "PLANNER-2026", "qty": 1, "name": "2026 Planner"}],
        "shipment": {"carrier": "ShipQuick", "tracking": "SQ1020", "status": "Label created"},
        "payment": {"method": "Visa", "status": "Pending"},
        "invoice": {"url": "https://example.com/invoice/HT1020", "amount": 21.0},
        "refund": {"status": "None", "amount": 0.0},
    },
}
